version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      java: corretto11
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
  build:
    commands:                               
      - echo Build started on `date`
      - echo Building java
      - cd auth-service-ecr
      - mvn clean package
      - echo Building the docker image
      - docker build -t auth-service-ecr
      - docker tag auth-service-ecr public.ecr.aws/p7x5b9x2/auth-service-ecr
  post_build:
    commands:
      - echo Build completed on `date`   
      - docker push public.ecr.aws/p7x5b9x2/auth-service-ecr
      - echo Writing definition files
      - printf '[{"name":"auth-service","imageUri":"%s"}]' public.ecr.aws/p7x5b9x2/auth-service-ecr > taskdefinition.json

artifacts:
  files: authorization-service/taskdefinition.json
