CREATE TABLE ROLES(
ID INTEGER,
NAME VARCHAR(20),
PRIMARY KEY(ID)
);

INSERT INTO roles(id, name) VALUES(1,'USER');
INSERT INTO roles(id, name) VALUES(2,'MODERATOR');
INSERT INTO roles(id, name) VALUES(3,'ADMIN');
